### ISSUE TITLE
[BUG] logger circular json bug

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-conx-core#23]
Need to look at the logger for the external api calls.  it's tossing an error about trying to convert a circular json structure.

15 [2023-10-25T20:58:00.191Z] [ERROR]: --- unhandledRejection --- TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at Logger.<anonymous> (/home/ted/vscode-f5/node_modules/f5-conx-core/src/logger.ts:183:45)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ted/vscode-f5/node_modules/f5-conx-core/dist/logger.js:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by DumpySquare** [comment]
wrapped in a try/catch statement to hide the errors.  This is happening at the json stringify/parse, which is used to cut out all the js functions which can be circular.

fixed in pending v1.1.0 release
